remove db connections from functions
sousajf1/skill-network pull request #24
Opened 2021-06-25 16:18 UTC by rego21

Issue: [#23](https://github.com/sousajf1/skill-network/issues/23)

- I followed the steps available at the following link: [Rocket: Databases](https://rocket.rs/v0.4/guide/state/#databases)
- I believe we can remove the "backend/database/mod.rs" file

2021-06-25 18:03 UTC, sousajf1 commented
Try to Run clippy localy 😄

2021-07-09 16:20 UTC, sousajf1 commented
Please rebase this

2021-07-09 22:02 UTC, sousajf1 commented
I've rebased this!

2021-07-12 09:58 UTC, luizchagasjardim requested changes

2021-07-12 09:58 UTC, luizchagasjardim commented on backend/Rocket.toml
> +sqlite_logs = { url = "test.db" }
Let's rename this, since the database does not hold logs.

2021-07-12 09:58 UTC, luizchagasjardim commented on backend/src/api/employee.rs
> +//use crate::database::establish_connection;
```suggestion
```

2021-07-12 09:58 UTC, luizchagasjardim commented on backend/src/api/employee_skill.rs
> +//use crate::database::establish_connection;
```suggestion
```

2021-07-12 09:58 UTC, luizchagasjardim commented on backend/src/api/employee_skill.rs
> +//use diesel::SqliteConnection;
```suggestion
```

2021-07-12 09:58 UTC, luizchagasjardim commented on backend/src/api/skill.rs
> +//use crate::database::establish_connection;
```suggestion
```

2021-07-12 09:58 UTC, luizchagasjardim commented on backend/src/main.rs
> +pub struct LogsDbConn(pub diesel::SqliteConnection);
I would change the name of this struct to just DbConn

2021-07-12 19:54 UTC, sousajf1 approved these changes
Lgtm!

2021-07-13 00:24 UTC, luizchagasjardim approved these changes
Very good!

2021-07-13 00:24 UTC, merged